# .peavers.yml - Addon metadata for peavers.io website

# Custom display name
name: Peavers CVars

# Icon to display on website
iconType: GearRuneIcon

# CurseForge project ID for download statistics
curseForgeProjectId: 1445775

# Tags for filtering and categorization
tags:
  - utility
  - settings
  - configuration
