apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: PeaversCVars
  description: "A World of Warcraft addon that lets you manage and persistently apply console variables (CVars) across logins."
  annotations:
    github.com/project-slug: peavers-warcraft/PeaversCVars
spec:
  type: library
  lifecycle: production
  owner: peavers-warcraft
